/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IERC20SOUL, IERC20SOULInterface } from "../IERC20SOUL";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "totalAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amountStaked",
            type: "uint256",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "expirationBlock",
                type: "uint256",
              },
            ],
            internalType: "struct IERC20SOUL.Schedule[]",
            name: "schedules",
            type: "tuple[]",
          },
        ],
        indexed: false,
        internalType: "struct IERC20SOUL.Lock",
        name: "lock",
        type: "tuple",
      },
    ],
    name: "LockExpired",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "totalAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amountStaked",
            type: "uint256",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "expirationBlock",
                type: "uint256",
              },
            ],
            internalType: "struct IERC20SOUL.Schedule[]",
            name: "schedules",
            type: "tuple[]",
          },
        ],
        indexed: false,
        internalType: "struct IERC20SOUL.Lock",
        name: "lock",
        type: "tuple",
      },
    ],
    name: "LockScheduleExpired",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "totalAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amountStaked",
            type: "uint256",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "expirationBlock",
                type: "uint256",
              },
            ],
            internalType: "struct IERC20SOUL.Schedule[]",
            name: "schedules",
            type: "tuple[]",
          },
        ],
        indexed: false,
        internalType: "struct IERC20SOUL.Lock",
        name: "lock",
        type: "tuple",
      },
      {
        indexed: false,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
    ],
    name: "LockedTransfer",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "totalAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amountStaked",
            type: "uint256",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "expirationBlock",
                type: "uint256",
              },
            ],
            internalType: "struct IERC20SOUL.Schedule[]",
            name: "schedules",
            type: "tuple[]",
          },
        ],
        internalType: "struct IERC20SOUL.Lock",
        name: "_lock",
        type: "tuple",
      },
    ],
    name: "transferWithLock",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IERC20SOUL__factory {
  static readonly abi = _abi;
  static createInterface(): IERC20SOULInterface {
    return new utils.Interface(_abi) as IERC20SOULInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC20SOUL {
    return new Contract(address, _abi, signerOrProvider) as IERC20SOUL;
  }
}
