/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { INetworkToken, INetworkTokenInterface } from "../INetworkToken";

const _abi = [
  {
    inputs: [],
    name: "getNetworkRoles",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class INetworkToken__factory {
  static readonly abi = _abi;
  static createInterface(): INetworkTokenInterface {
    return new utils.Interface(_abi) as INetworkTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): INetworkToken {
    return new Contract(address, _abi, signerOrProvider) as INetworkToken;
  }
}
