/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Signer,
  utils,
  BigNumberish,
  Contract,
  ContractFactory,
  Overrides,
} from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PriceOracle, PriceOracleInterface } from "../PriceOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_price",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "getPriceInPPT",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "price",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_price",
        type: "uint256",
      },
    ],
    name: "setPrice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161032338038061032383398181016040528101906100329190610054565b80600081905550506100a7565b60008151905061004e81610090565b92915050565b60006020828403121561006a5761006961008b565b5b60006100788482850161003f565b91505092915050565b6000819050919050565b600080fd5b61009981610081565b81146100a457600080fd5b50565b61026d806100b66000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c8063338f1ce61461004657806391b7f5ed14610064578063a035b1fe14610080575b600080fd5b61004e61009e565b60405161005b9190610196565b60405180910390f35b61007e60048036038101906100799190610117565b6100a7565b005b6100886100fc565b6040516100959190610196565b60405180910390f35b60008054905090565b6103e863ffffffff168111156100f2576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004016100e990610176565b60405180910390fd5b8060008190555050565b60005481565b60008135905061011181610220565b92915050565b60006020828403121561012d5761012c6101cc565b5b600061013b84828501610102565b91505092915050565b60006101516031836101b1565b915061015c826101d1565b604082019050919050565b610170816101c2565b82525050565b6000602082019050818103600083015261018f81610144565b9050919050565b60006020820190506101ab6000830184610167565b92915050565b600082825260208201905092915050565b6000819050919050565b600080fd5b7f50726963654f7261636c653a206e6577205f7072696365206d7573742062652060008201527f67726561746572207468616e2031303030000000000000000000000000000000602082015250565b610229816101c2565b811461023457600080fd5b5056fea26469706673582212205053a79a8c4447512dc4c9d61eca72a3f6e827b5d324b92139b8ee90e6851f4164736f6c63430008070033";

export class PriceOracle__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    _price: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<PriceOracle> {
    return super.deploy(_price, overrides || {}) as Promise<PriceOracle>;
  }
  getDeployTransaction(
    _price: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_price, overrides || {});
  }
  attach(address: string): PriceOracle {
    return super.attach(address) as PriceOracle;
  }
  connect(signer: Signer): PriceOracle__factory {
    return super.connect(signer) as PriceOracle__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PriceOracleInterface {
    return new utils.Interface(_abi) as PriceOracleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PriceOracle {
    return new Contract(address, _abi, signerOrProvider) as PriceOracle;
  }
}
